### ISSUE TITLE
Out of bounds error in create_random_crops()

### ISSUE THREAD

**Issue by bart-lg** [bart-lg/geocropper#15]
Traceback (most recent call last):
  File "generate_random_crops.py", line 2, in <module>
    geocropper.utils.create_random_crops()
  File "/data/projects/windturbine-identification-sentinel/geoc-symlinks/geocropper/geocropper/utils.py", line 386, in create_random_crops
    pixel_val = array[y_index, x_index]
IndexError: index 10980 is out of bounds for axis 1 with size 10980

**Comment by bart-lg** [comment]
The tile area where the random point is generated randomly is now reduced by half of the crop height and width
