### ISSUE TITLE
Handle different HTTP Codes in replies of API requests

### ISSUE THREAD

**Issue by bart-lg** [bart-lg/geocropper#19]
Search for Sentinel data:
lat: 31.277945
lon: -101.142479
From: 01.07.2020
To: 30.09.2020
Platform: Sentinel-1
Tile-limit: 1
producttype: GRD
----------------------------

Traceback (most recent call last):
  File "scripts/import_all_CSVs.py", line 6, in <module>
    geocropper.importAllCSVs()
  File "../geocropper/geocropper/geocropper.py", line 50, in importAllCSVs
    csvImport.importAllCSVs(delimiter, quotechar)
  File "../geocropper/geocropper/csvImport.py", line 42, in importAllCSVs
    loadImportedCSVdata()
  File "../geocropper/geocropper/csvImport.py", line 140, in loadImportedCSVdata
    width = item["width"], height = item["height"], tileLimit = item["tileLimit"], **kwargs)
  File "../geocropper/geocropper/geocropper.py", line 908, in downloadAndCrop
    products = self.downloadSentinelData(dateFrom, dateTo, platform, poiId=poiId, tileLimit=tileLimit, **kwargs)
  File "../geocropper/geocropper/geocropper.py", line 179, in downloadSentinelData
    products = self.sentinel.getSentinelProducts(self.lat, self.lon, dateFrom, dateTo, platform, limit=tileLimit, **kwargs)
  File "../geocropper/geocropper/sentinelWrapper.py", line 37, in getSentinelProducts
    result = self.api.query(footprint, date=(dateFrom, dateTo), platformname=platform, **kwargs)
  File "/home/bleongruchalski/.conda/envs/env/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 147, in query

  File "/home/bleongruchalski/.conda/envs/env/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 272, in _load_query
    # Allow None to be used as a unlimited bound
  File "/home/bleongruchalski/.conda/envs/env/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 304, in _load_subquery
    order_by: str, optional
  File "/home/bleongruchalski/.conda/envs/env/lib/python3.7/site-packages/sentinelsat/sentinel.py", line 1027, in _check_scihub_response
    if paths:
sentinelsat.sentinel.SentinelAPIError: HTTP status 500 Internal Server Error: SolrServerException : Server refused connection at: http://172.30.175.85:8983/solr/dhus
Makefile:3: recipe for target 'importall' failed
make: *** [importall] Error 1

**Comment by bart-lg** [comment]
The HTTP code 500 has nothing to do with the request itself by the way...

**Comment by bart-lg** [comment]
Probable solution for 500 codes:
If a retry parameter in config is set, the script waits for e.g. 1 hour until it tries again for some time (12 hours?).

**Comment by bart-lg** [comment]
Exception handled for Sentinel products only.
Exception handling for Landsat still outstanding.
